Release - New GitHub workflow for releasing
Adyen/adyen-android pull request #1847
Opened 2024-10-21 15:00 UTC by araratthehero

## Description
- Created a duplicate `publish_release` workflow, which allows running the job on a specified branch
- Use new Github secrets for publishing the app on maven central
- Make the Github release draft

## Things to do in the future
- Add a step to verify if the branch name starts with e.g. `release/`

## Checklist 
- [x] PR is labelled 
- [ ] Changes are tested manually

COAND-1013

2024-10-21 15:11 UTC, jreij commented
PR base should not be `main`, the current release process requires `develop` to be up to date with `main` so we cannot merge anything directly to `main` before we are fully ready to remove the old release process

2024-10-22 08:58 UTC, araratthehero commented on .github/workflows/publish_release_manual.yml
> +          ref: main
This needs to change. It should be the branch on which we triggered the action.

2024-10-22 14:50 UTC, jreij requested changes
Once we merge the feature branch we will lose the old request action, can we instead keep it and name it something like `old`?

2024-10-23 10:20 UTC, araratthehero commented on .github/workflows/publish_release_old.yml
> +          PROJECT_VERSION=$(./scripts/version_name.sh)
This need to be updated when [this PR](https://github.com/Adyen/adyen-android/pull/1814) is merged.

2024-10-23 10:20 UTC, araratthehero commented on .github/workflows/publish_release_old.yml
> +          PROJECT_VERSION=$(./scripts/version_name.sh)
Similarly the `publish_release.yml` as well

2024-10-24 07:17 UTC, araratthehero commented on .github/workflows/publish_release_old.yml
> +          PROJECT_VERSION=$(./scripts/version_name.sh)
We do not have to wait for that PR anymore. The changes made [here](https://github.com/Adyen/adyen-android/pull/1848) are enough.

2024-10-24 07:56 UTC, jreij approved these changes

2024-10-24 08:01 UTC, merged